### ISSUE TITLE
Publish 0.4.2 to npm please

### ISSUE THREAD

**Issue by hartzis** [emostar/express-graceful-exit#12]
Can you get 0.4.2 published to npm please. 😸 

- fixes `undefined socket array error`
  - https://github.com/emostar/express-graceful-exit/issues/10
  - https://github.com/emostar/express-graceful-exit/commit/8400a23ac6dd98df0cea5cb8549f9a5201ea42eb

It is not up there
- https://yarnpkg.com/en/package/express-graceful-exit
- https://www.npmjs.com/package/express-graceful-exit

**Comment by ivolucien** [comment]
@hartzis - thanks for the nudge!

_waves cheerfully_
