### ISSUE TITLE
Suicide shutdown is disabled when exitProcess is false

### ISSUE THREAD

**Issue by boblauer** [emostar/express-graceful-exit#13]
I understand wanting to set `exitProcess` to false to handle shutdown in a custom manner. However, I was surprised to find that doing so also disables the suicide shutdown. I would consider those two things to be separate, as in "I'll handle closing everything myself, but I would still like shutdown to happen after 2 minutes if clean up is not done by then."

It's simple enough to implement a custom suicide routine, but obviously it would be nicer if this package handled it automatically.

Is suicide shutdown being tied to `exitProcess` intentional, or an oversight?

**Comment by ivolucien** [comment]
@boblauer - there simply hasn't been any interest expressed in that previously, it could easily be added. I'd be happy to merge a PR along those lines, as long as it doesn't break existing behavior. And if anyone else up-votes this I could implement it myself in the medium term.   :-)

**Comment by ivolucien** [comment]
@boblauer - I'm closing this issue and adding the design question you raise as a +1 feature request.

I'm happy to reopen it if you have something to add or a PR to put forward.
